
---
  title: "Bioturbation"
  output: "html_document"
---
## DataRepository
 Repository 10.11922/sciencedb.01316

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```
## Analysis of Bacterial community
```{r}
# Packages needed to run this code
library(vegan)
library(tidyverse)
library('BiodiversityR')
library(devtools)
library(pairwiseAdonis)
library(mvabund)
library(ggplot2)
library(gridExtra)
library(cowplot)
library(rmarkdown)
library(RVAideMemoire)
```

```{r}
setwd("~/Dropbox/Articoli/PLOT/0_PLOT_MS_NEW/0_Mature/mSystem_Revision2/RScript and data/")
# LOAD DATA AND PREPARE IT FOR ANALISIS
otu_mat<-read.table("OTU_mat.txt",header=T,sep="\t",row.names = 1)
map_mat<-read.table("map_mat.txt",header=T,sep="\t")

# Transformation of the data for homogeneity
otu_mat<-log10(otu_mat+1)

#This is for testing the full set of explanatory variable
your.matrix.distance.BC.mat<- vegdist(otu_mat, method="bray")
mat<-adonis2(your.matrix.distance.BC.mat ~ DEPTH*MONTH*CRAB, data = map_mat, block=PLOT)
summary(mat)
map_mat$facator_all<-factor(paste(map_mat$MONTH,map_mat$CRAB,map_mat$DEPTH,sep = "_"))
mat2<-adonis2(your.matrix.distance.BC.mat ~ facator_all, data = map_mat, block=PLOT)
```

# analysis of pH
```{r}
pH<-read.table("~/Dropbox/Articoli/PLOT/NEW_analysis/biochemistry/pH.txt",header=T,sep="\t")
pH$DEPTH<-factor(pH$DEPTH,level=c("S","SS","D"), labels=c("S","SS","D"))
pH$SITE<-factor(pH$SITE,level=c("MATURE","JUVENILE"), labels=c("MATURE","JUVENILE"))
pH<-na.omit(pH)
pH_m<-subset(pH,SITE=='MATURE')


summary(pH_m)
model2<-manylm(pH~DEPTH*factor(MONTH), pH_m)
plotty<-factor(pH_m$PLOT)
anova(model2, block = 'plotty', resamp='case', test="F")
```
## analysis of Salinity

```{r}
sal<-read.table("~/Dropbox/Articoli/PLOT/NEW_analysis/biochemistry/SALINITY.txt",header=T,sep="\t")
sal$DEPTH<-factor(sal$DEPTH,level=c("S","SS","D"), labels=c("S","SS","D"))
sal$SITE<-factor(sal$SITE,level=c("MATURE","JUVENILE"), labels=c("MATURE","JUVENILE"))
sal<-na.omit(sal)
sal_m<-subset(sal,SITE=='MATURE')


summary(sal_m)
model2<-manylm(SALINITY~DEPTH*factor(MONTH), sal_m)
plotty<-factor(sal_m$PLOT)
anova(model2, block = 'plotty', resamp='case', test="F")
```

## Multivariate analysis of the biochemical parameters
```{r}
biochem<-read.table("~/Dropbox/Articoli/PLOT/NEW_analysis/biochemistry/BIOCHEMISTRY.txt",header=T,sep="\t")

biochem1<-subset(biochem, biochem$SITE=="MATURE")
biochem2<-subset(biochem1, biochem$BIOTURBATION!="NONE")

biochem.mod <- manylm(cbind(pH,Nitrite,
                            Phosphate,Silicate,Nitrate,POC,PIC,PIN,PON) ~ 
                            DEPTH * MONTH2 * BIOTURBATION,
                  data=biochem2)
plotty<-factor(biochem2$PLOT)
summary(biochem.mod, block = 'plotty', resamp='case', test="LR")
anova(biochem.mod)

biochem2<-na.omit(biochem2)
biochem2$DEPTH<-factor(biochem2$DEPTH,level=c("S","SS","D"), labels=c("Surface","SubSurface","Deep"))
biochem2$MONTH2<-factor(biochem2$MONTH2,levels = c("May-16","Aug-16","Nov-16","Feb-17","May-17","Aug-17"))


Sulphate<-ggplot(biochem2, aes(x=BIOTURBATION, y=Sulphate, fill=DEPTH)) + 
  geom_boxplot(notch=TRUE)+ 
  facet_grid(~MONTH2)+
  scale_fill_manual(values=c("dodgerblue1","orange1","snow4"))+
  xlab("") + 
  ylab(bquote('Sulphate (ug S/mg dry sediment)\n')) +
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_blank(), 
        axis.title.x = element_blank(), axis.text.y = element_text(size = 6), 
        axis.title.y = element_text(size = 6), strip.text = element_text(size = 6)) 

Nitrite<-ggplot(biochem2, aes(x=BIOTURBATION, y=Nitrite, fill=DEPTH)) + 
  geom_boxplot(notch=TRUE)+ 
  facet_grid(~MONTH2)+
  scale_fill_manual(values=c("dodgerblue1","orange1","snow4"))+
  xlab("") + 
  ylab(bquote('Nitrite (ug S/mg dry sediment)\n')) +
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_blank(), 
        axis.title.x = element_blank(), axis.text.y = element_text(size = 6),
        axis.title.y = element_text(size = 6), strip.text = element_text(size = 6)) 

Phosphate<-ggplot(biochem2, aes(x=BIOTURBATION, y=Phosphate, fill=DEPTH)) + 
  geom_boxplot(notch=TRUE)+ 
  facet_grid(~MONTH2)+
  scale_fill_manual(values=c("dodgerblue1","orange1","snow4"))+
  xlab("") + 
  ylab(bquote('Phosphate (ug S/mg dry sediment)\n')) +
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_blank(), 
        axis.title.x = element_blank(), axis.text.y = element_text(size = 6), 
        axis.title.y = element_text(size = 6), strip.text = element_text(size = 6)) 


Silicate<-ggplot(biochem2, aes(x=BIOTURBATION, y=Silicate, fill=DEPTH)) + 
  geom_boxplot(notch=TRUE)+ 
  facet_grid(~MONTH2)+
  scale_fill_manual(values=c("dodgerblue1","orange1","snow4"))+
  xlab("Bioturbation intensity") + 
  ylab(bquote('Silicate (ug S/mg dry sediment)\n')) +
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_text(size = 6), 
        axis.title.x = element_text(size = 6), axis.text.y = element_text(size = 6), 
        axis.title.y = element_text(size = 6), strip.text = element_text(size = 6))

Nitrate<-ggplot(biochem2, aes(x=BIOTURBATION, y=Nitrate, fill=DEPTH)) + 
  geom_boxplot(notch=TRUE)+ 
  facet_grid(~MONTH2)+
  scale_fill_manual(values=c("dodgerblue1","orange1","snow4"))+
  xlab("") + 
  ylab(bquote('Nitrate (ug S/mg dry sediment)\n')) +
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_blank(), 
        axis.title.x = element_blank(), axis.text.y = element_text(size = 6), 
        axis.title.y = element_text(size = 6), strip.text = element_text(size = 6)) 

POC<-ggplot(biochem2, aes(x=BIOTURBATION, y=POC, fill=DEPTH)) + 
  geom_boxplot(notch=TRUE)+ 
  facet_grid(~MONTH2)+
  scale_fill_manual(values=c("dodgerblue1","orange1","snow4"))+
  xlab("") + 
  ylab(bquote('POC (ug S/mg dry sediment)\n')) +
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_blank(), 
        axis.title.x = element_blank(), axis.text.y = element_text(size = 6), 
        axis.title.y = element_text(size = 6), strip.text = element_text(size = 6)) 

PIC<-ggplot(biochem2, aes(x=BIOTURBATION, y=PIC, fill=DEPTH)) + 
  geom_boxplot(notch=TRUE)+ 
  facet_grid(~MONTH2)+
  scale_fill_manual(values=c("dodgerblue1","orange1","snow4"))+
  xlab("") + 
  ylab(bquote('PIC (ug S/mg dry sediment)\n')) +
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_blank(), 
        axis.title.x =element_blank(), axis.text.y = element_text(size = 6), 
        axis.title.y = element_text(size = 6), strip.text = element_text(size = 6)) 


PIN<-ggplot(biochem2, aes(x=BIOTURBATION, y=PIN, fill=DEPTH)) + 
  geom_boxplot(notch=TRUE)+ 
  facet_grid(~MONTH2)+
  scale_fill_manual(values=c("dodgerblue1","orange1","snow4"))+
  xlab("") + 
  ylab(bquote('PIN (ug S/mg dry sediment)\n')) +
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_blank(), 
        axis.title.x = element_blank(), axis.text.y = element_text(size = 6), 
        axis.title.y = element_text(size = 6), strip.text = element_text(size = 6)) 

PON<-ggplot(biochem2, aes(x=BIOTURBATION, y=PON, fill=DEPTH)) + 
  geom_boxplot(notch=TRUE)+ 
  facet_grid(~MONTH2)+
  scale_fill_manual(values=c("dodgerblue1","orange1","snow4"))+
  ylab(bquote('PON (ug S/mg dry sediment)\n')) +
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_blank(), 
        axis.title.x = element_blank(), axis.text.y = element_text(size = 6), 
        axis.title.y = element_text(size = 6), strip.text = element_text(size = 6)) 

PH<-ggplot(biochem2, aes(x=BIOTURBATION, y=pH, fill=DEPTH)) + 
  geom_boxplot(notch=TRUE)+ 
  facet_grid(~MONTH2)+
  scale_fill_manual(values=c("dodgerblue1","orange1","snow4"))+
  xlab("Bioturbation intensity") + 
  ylab("pH") +
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_text(size = 6), 
        axis.title.x = element_text(size = 6), axis.text.y = element_text(size = 6), 
        axis.title.y = element_text(size = 6), strip.text = element_text(size = 6))

plot_grid(POC,PON,PIC,PIN,Phosphate,Nitrite, Nitrate, Silicate,Sulphate,PH, ncol=2, nrow=5, align="v")

```

##  analysis of alpha-diversity indexes
```{r}
#Preparation of the data
divers<-read.table("~/Dropbox/Articoli/PLOT/NEW_analysis/divrich/divrich.txt",header=T,sep="\t")
divers$DEPTH<-factor(divers$DEPTH,level=c("S","SS","D"), labels=c("S","SS","D"))
divers$SITE<-factor(divers$SITE,level=c("MATURE","JUVENILE"), labels=c("MATURE","JUVENILE"))
divers<-na.omit(divers)
divers_m<-subset(divers,SITE=='MATURE')
divers_m<-subset(divers_m,BIOTURBATION!='NONE')
unique(divers_m$MONTH2)
divers_m$MONTH2<-factor(divers_m$MONTH2,levels = c("May-16","Aug-16","Nov-16","Feb-17","May-17","Aug-17"))
divers_m$BIOTURBATION<-factor(divers_m$BIOTURBATION,levels = c("HIGH","MEDIUM"), labels = c("HIGH","NORMAL"))

#tests
summary(divers_m)
model2<-manylm(log(H)~BIOTURBATION*DEPTH*factor(MONTH), divers_m)
plotty<-factor(divers_m$PLOT)
anova(model2, block = 'plotty', resamp='case', test="F")

model2<-manylm(log(N)~BIOTURBATION*DEPTH*factor(MONTH), divers_m)
plotty<-factor(divers_m$PLOT)
anova(model2, block = 'plotty', resamp='case', test="F")

#graphs
Shannon<-ggplot(divers_m, aes(x=BIOTURBATION, y=H, fill=DEPTH)) + 
  geom_boxplot(notch=TRUE)+ 
  facet_grid(~MONTH2)+
  scale_fill_manual(values=c("dodgerblue1","orange1","snow4"))+
  xlab("Bioturbation intensity") + 
  ylab("Diversity (H)") +
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_text(size = 6), 
        axis.title.x = element_text(size = 6), axis.text.y = element_text(size = 6), 
        axis.title.y = element_text(size = 6), strip.text = element_text(size = 6))


Richness<-ggplot(divers_m, aes(x=BIOTURBATION, y=N, fill=DEPTH)) + 
  geom_boxplot(notch=TRUE)+ 
  facet_grid(~MONTH2)+
  scale_fill_manual(values=c("dodgerblue1","orange1","snow4"))+
  xlab("Bioturbation intensity") + 
  ylab("Richness (J)") +
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_text(size = 6), 
        axis.title.x = element_text(size = 6), axis.text.y = element_text(size = 6), 
        axis.title.y = element_text(size = 6), strip.text = element_text(size = 6))



```

##  analysis of qPCR
```{r}
#import and preparation of the data
qpcr<-read.table("~/Dropbox/Articoli/PLOT/NEW_analysis/qpcr/qpcr_mature.txt",header=T,sep="\t")
qpcr$Depth<-factor(qpcr$Depth,level=c("S","SS","D"), labels=c("Surface","SubSurface","Deep"))
qpcr$Stage<-factor(qpcr$Stage,level=c("MATURE","JUVENILE"), labels=c("MATURE","JUVENILE"))
qpcr<-na.omit(qpcr)
qpcr_m<-subset(qpcr,Stage=='MATURE')
qpcr_m<-subset(qpcr_m,BioT!='NONE')
qpcr_m$MONTH<-factor(qpcr_m$MONTH,levels = c("May-16","Aug-16","Nov-16","Feb-17","May-17","Aug-17"))
qpcr_m$BioT<-factor(qpcr_m$BioT,levels = c("HIGH","LOW"), labels = c("HIGH","NORMAL"))

#tests
summary(qpcr_m)
model2<-manylm(log(Copies)~BioT*Depth*MONTH, qpcr_m)
plotty<-factor(qpcr_m$PLOT)
anova(model2, block = 'plotty', resamp='case', test="LR")

#graph
bacterio_a<-ggplot(qpcr_m,aes(BioT,log(Copies),fill=Depth))+ 
  geom_boxplot(notch=TRUE)+
  scale_fill_manual(values=c("dodgerblue1","orange1","snow4"))+
  ylab("Log Bacterial 16S Copies / gr sediment")+ 
  facet_grid(~MONTH) +
  xlab("Bioturbation intensity") +
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_text(size = 6), 
        axis.title.x = element_text(size = 6), axis.text.y = element_text(size = 6), 
        axis.title.y = element_text(size = 6), strip.text = element_text(size = 6))




```
##  analysis of Fluorescine diacetate
```{R}
#importing and formatting data
fda<-read.table("~/Dropbox/Articoli/PLOT/NEW_analysis/fda/FDA_mature.txt",header=T,sep="\t")
fda$Depth<-factor(fda$Depth,level=c("S","SS","D"), labels=c("Surface","SubSurface","Deep"))
fda$MONTH<-factor(fda$MONTH,levels = c("May-16","Aug-16","Nov-16","Feb-17","May-17","Aug-17"),labels=c("May-16","Aug-16","Nov-16","Feb-17","May-17","Aug-17"))
fda$SITE<-factor(fda$SITE,levels = c("MATURE","JUVENILE"), labels=c("MATURE","JUVENILE"))

fda$Crab<-factor(fda$Crab,levels = c("HIGH","MEDIUM"), labels = c("HIGH","NORMAL"))

fda<-na.omit(fda)

fda_m<-subset(fda,SITE=='MATURE')
fda_m<-subset(fda_m,Crab!="NONE")
#testing
summary(fda_m)
model2<-manylm(log(Fluorescein)~Crab*Depth*MONTH, fda_m)
plotty<-factor(fda_m$Plot)
anova(model2, block = 'plotty',resamp='case', test="LR")

#graph
fda_plot<-ggplot(fda_m, aes(x=Crab, y=Fluorescein, fill=Depth)) + 
  geom_boxplot(notch=TRUE)+
  facet_grid(~MONTH)+
  scale_fill_manual(values = c("dodgerblue1","orange1","snow4")) +
  xlab("Bioturbation intensity") +
  ylab(bquote("Fluorescein (mg "*g^-1*"sediment 3"*h^-1*")")) +
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_text(size = 6), 
        axis.title.x = element_text(size = 6), axis.text.y = element_text(size = 6), 
        axis.title.y = element_text(size = 6), strip.text = element_text(size = 6))

```

##  Assemblage Figure S5
```{r}

plot_grid(Shannon,Richness,bacterio_a,fda_plot, ncol=1, nrow=4, align="v",axis = 'l')


```


##  analysis of bacterial function
```{r}
funcmat<-read.table("~/Dropbox/Articoli/PLOT/NEW_analysis/function/func_table_reduced_MATURE.txt",header=T,sep="\t")
funcmat<-na.omit(funcmat)
funcmat<-subset(funcmat, funcmat$BIOTURBATION!="NONE")
funcmat$DEPTH<-factor(funcmat$DEPTH,level=c("S","SS","D"), labels=c("Surface","SubSurface","Deep"))
funcmat$BIOTURBATION<-factor(funcmat$BIOTURBATION,levels = c("HIGH","LOW"), labels = c("HIGH","NORMAL"))

attach(funcmat)

str(funcmat)

func.matrix.distance.bray.mat<- vegdist(funcmat[, c(8:41)], method="bray")
func_test<-adonis2(log10(funcmat[, c(8:41)]+1) ~ DEPTH* MONTH *BIOTURBATION,data=funcmat, block=PLOT,na.rm=TRUE)

funcmat$MONTH<-factor(funcmat$MONTH,levels = c("May-16","Aug-16","Nov-16","Feb-17","May-17","Aug-17"))

photoauto<-ggplot(funcmat, aes(x=BIOTURBATION, y=photoautotrophy, fill=DEPTH)) + 
  geom_boxplot(notch=TRUE)+
  facet_grid(~MONTH)+
  scale_fill_manual(values=c("dodgerblue1","orange1","snow4"))+
  xlab("Bioturbation Intensity") +
  ylab(bquote('Photoautotrophy')) + 
  theme_classic()+
   theme(legend.position = "none",
        axis.text.x = element_text(size = 6), 
        axis.title.x = element_text(size = 6), axis.text.y = element_text(size = 6), 
        axis.title.y = element_text(size = 6), strip.text = element_text(size = 6))

sulfate_resp<-ggplot(funcmat, aes(x=BIOTURBATION, y=sulfate_respiration, fill=DEPTH)) + 
  geom_boxplot(notch=TRUE)+
  facet_grid(~MONTH)+
  scale_fill_manual(values=c("dodgerblue1","orange1","snow4"))+
  xlab("Bioturbation Intensity") +
  ylab(bquote('Sulfate respiration')) +
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_text(size = 6), 
        axis.title.x = element_text(size = 6), axis.text.y = element_text(size = 6), 
        axis.title.y = element_text(size = 6), strip.text = element_text(size = 6))

Cell<-ggplot(funcmat, aes(x=BIOTURBATION, y=cellulolysis, fill=DEPTH)) + 
  geom_boxplot(notch=TRUE)+
  facet_grid(~MONTH)+
  scale_fill_manual(values=c("dodgerblue1","orange1","snow4"))+
  xlab("Bioturbation Intensity") +
  ylab(bquote('Cellulolysis')) + 
  theme_classic()+
 theme(legend.position = "none",
        axis.text.x = element_text(size = 6), 
        axis.title.x = element_text(size = 6), axis.text.y = element_text(size = 6), 
        axis.title.y = element_text(size = 6), strip.text = element_text(size = 6))


Nitri<-ggplot(funcmat, aes(x=BIOTURBATION, y=nitrification, fill=DEPTH)) + 
  geom_boxplot(notch=TRUE)+
  facet_grid(~MONTH)+
  scale_fill_manual(values=c("dodgerblue1","orange1","snow4"))+
  xlab("Bioturbation Intensity") +
  ylab(bquote('Nitrification')) + 
  theme_classic()+
   theme(legend.position = "none",
        axis.text.x = element_text(size = 6), 
        axis.title.x = element_text(size = 6), axis.text.y = element_text(size = 6), 
        axis.title.y = element_text(size = 6), strip.text = element_text(size = 6))

nitrate_red<-ggplot(funcmat, aes(x=BIOTURBATION, y=nitrate_reduction, fill=DEPTH)) + 
  geom_boxplot(notch=TRUE)+
  facet_grid(~MONTH)+
  scale_fill_manual(values=c("dodgerblue1","orange1","snow4"))+
  xlab("Bioturbation Intensity") +
  ylab(bquote('Nitrate reduction')) + 
  theme_classic()+
   theme(legend.position = "none",
        axis.text.x = element_text(size = 6), 
        axis.title.x = element_text(size = 6), axis.text.y = element_text(size = 6), 
        axis.title.y = element_text(size = 6), strip.text = element_text(size = 6))

photoheterotrophy<-ggplot(funcmat, aes(x=BIOTURBATION, y=photoheterotrophy, fill=DEPTH)) + 
  geom_boxplot(notch=TRUE)+
  facet_grid(~MONTH)+
  scale_fill_manual(values=c("dodgerblue1","orange1","snow4"))+
  xlab("Bioturbation Intensity") +
  ylab(bquote('Photoheterotrophy')) + 
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_text(size = 6), 
        axis.title.x = element_text(size = 6), axis.text.y = element_text(size = 6), 
        axis.title.y = element_text(size = 6), strip.text = element_text(size = 6))

Nfixation<-ggplot(funcmat, aes(x=BIOTURBATION, y=nitrogen_fixation, fill=DEPTH)) + 
  geom_boxplot(notch=TRUE)+
  facet_grid(~MONTH)+
  scale_fill_manual(values=c("dodgerblue1","orange1","snow4"))+
  xlab("Bioturbation Intensity") +
  ylab(bquote('Nitrogen fixation')) + 
  theme_classic()+
   theme(legend.position = "none",
        axis.text.x = element_text(size = 6), 
        axis.title.x = element_text(size = 6), axis.text.y = element_text(size = 6), 
        axis.title.y = element_text(size = 6), strip.text = element_text(size = 6))

Sulphi_respiration<-ggplot(funcmat, aes(x=BIOTURBATION, y=sulfite_respiration, fill=DEPTH)) + 
  geom_boxplot(notch=TRUE)+
  facet_grid(~MONTH)+
  scale_fill_manual(values=c("dodgerblue1","orange1","snow4"))+
  xlab("Bioturbation Intensity") +
  ylab(bquote('Sulphite respiration')) + 
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_text(size = 6), 
        axis.title.x = element_text(size = 6), axis.text.y = element_text(size = 6), 
        axis.title.y = element_text(size = 6), strip.text = element_text(size = 6))


plot_grid(photoauto,sulfate_resp,Cell,Nitri,nitrate_red,photoheterotrophy ,Nfixation,Sulphi_respiration, ncol=2, nrow=4, align="v",axis = 'l')


```




##  Plant performance
```{r}
setwd("~/Dropbox/Articoli/PLOT/NEW_analysis/plantgrowth")


matplant1<-read.table("~/Dropbox/Articoli/PLOT/NEW_analysis/plantgrowth/plant_mat1.txt",header=T,sep="\t")
matplant2<-read.table("~/Dropbox/Articoli/PLOT/NEW_analysis/plantgrowth/plant_mat2.txt",header=T,sep="\t")


matplant1$MONTH2<-factor(matplant1$MONTH2,level=c("May-16","Aug-16","Nov-16","Feb-17","May-17","Aug-17"),labels=c("May-16","Aug-16","Nov-16","Feb-17","May-17","Aug-17"))

#ancova with biot as continuous

model.pneu<-aov(log(PNEUM+1)~BIOT*MONTH, matplant1)
anova(model.pneu)

model.height<-aov(log(HEIGHT+1)~BIOT*MONTH, matplant1)
anova(model.height)


matplant2$MONTH2<-factor(matplant2$MONTH2,level=c("May-16","Aug-16","Nov-16","Feb-17","May-17","Aug-17"),labels=c("May-16","Aug-16","Nov-16","Feb-17","May-17","Aug-17"))

matplant2<-na.omit(matplant2)

#ancova with biot as continuous
summary(matplant2)
model.branch<-aov(log(BRANCH+1)~BIOTURBATION*MONTH2, matplant2)
anova(model.branch)


##plot

pneu<-ggplot(matplant1, aes(x=MONTH2, y=PNEUM, fill=BIOT)) + 
  geom_boxplot()+
  xlab("")+
  ylab(bquote('Number of pneumatophores\n'))+
  theme_bw()+
  scale_fill_manual(values = c("red4", "red"))+
  theme(panel.border = element_blank(), legend.position = "none",
        panel.grid.major = element_blank(),panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"), axis.text.x = element_text(size = 10), 
        axis.title.x = element_text(size = 10), axis.text.y = element_text(size = 10), 
        axis.title.y = element_text(size = 10))

height<-ggplot(matplant1, aes(x=MONTH2, y=HEIGHT, fill=BIOT)) + 
  geom_boxplot()+
  xlab("")+
  ylab(bquote('Height (cm)'))+
  theme_bw()+
  scale_fill_manual(values = c("red4", "red"))+
  theme(panel.border = element_blank(), legend.position = "none",
        panel.grid.major = element_blank(),panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"), axis.text.x = element_text(size = 10), 
        axis.title.x = element_text(size = 10), axis.text.y = element_text(size = 10), 
        axis.title.y = element_text(size = 10))


branch<-ggplot(matplant2, aes(x=MONTH2, y=BRANCH, fill=BIOTURBATION)) + 
  geom_boxplot()+
  xlab("Time")+
  ylab(bquote('Branch diameter (mm)'))+
  theme_bw()+
  scale_fill_manual(values = c("red4", "red"))+
  theme(panel.border = element_blank(), legend.position = "bottom",
        panel.grid.major = element_blank(),panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"), axis.text.x = element_text(size = 10), 
        axis.title.x = element_text(size = 10), axis.text.y = element_text(size = 10), 
        axis.title.y = element_text(size = 10))

plot_grid(pneu,height,branch, align="v",axis = 'l',ncol = 1, labels = c("A","B","C"))


```

